DROP DATABASE IF EXISTS mvp

CREATE DATABASE mvp;

CREATE TABLE white_cards (id INT AUT0_INCREMENT NOT NULL, text VARCHAR);

CREATE TABLE black_cards (id INT AUT0_INCREMENT NOT NULL, text VARCHAR, pick INT);